```python
#!/usr/bin/env python3

import argparse
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import (
    ModelCheckpoint,
    EarlyStopping,
    ReduceLROnPlateau
)
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split


# =========================================================
# Arguments
# =========================================================

parser = argparse.ArgumentParser(
    description="Train LSTM SMILES Generator"
)

parser.add_argument(
    "--smiles",
    required=True,
    help="Filtered SMILES CSV file"
)

parser.add_argument(
    "--tokenizer",
    required=True,
    help="Tokenizer file generated by prepare_smiles.py"
)

parser.add_argument(
    "--epochs",
    type=int,
    default=1000,
    help="Number of epochs (default=1000)"
)

parser.add_argument(
    "--batch_size",
    type=int,
    default=256,
    help="Batch size (default=256)"
)

parser.add_argument(
    "--learning_rate",
    type=float,
    default=0.0005,
    help="Learning rate (default=0.0005)"
)

parser.add_argument(
    "--embedding_dim",
    type=int,
    default=256,
    help="Embedding dimension (default=256)"
)

parser.add_argument(
    "--lstm_units",
    type=int,
    default=512,
    help="LSTM units (default=512)"
)

parser.add_argument(
    "--dropout",
    type=float,
    default=0.3,
    help="Dropout rate (default=0.3)"
)

parser.add_argument(
    "--output",
    default="Final_base_model.weights.h5",
    help="Output weights file"
)

args = parser.parse_args()


# =========================================================
# Load Data
# =========================================================

print(f"\nLoading SMILES from: {args.smiles}")

df = pd.read_csv(args.smiles)

if "smiles" not in df.columns:
    raise ValueError(
        "Input CSV must contain a column named 'smiles'"
    )

smiles_list = (
    df["smiles"]
    .astype(str)
    .str.strip()
    .tolist()
)

print(f"Training molecules: {len(smiles_list)}")


# =========================================================
# Load Tokenizer
# =========================================================

print(f"Loading tokenizer: {args.tokenizer}")

with open(args.tokenizer, "rb") as f:
    tokenizer = pickle.load(f)

char2idx = tokenizer["char2idx"]
idx2char = tokenizer["idx2char"]

vocab_size = tokenizer["vocab_size"]
max_len = tokenizer["max_len"]

print(f"Vocabulary size: {vocab_size}")
print(f"Maximum sequence length: {max_len}")


# =========================================================
# Tokenization
# =========================================================

def tokenize(smile):

    return [
        char2idx[c]
        for c in smile
    ]


tokenized = [
    tokenize(s)
    for s in smiles_list
]

input_seqs = pad_sequences(
    tokenized,
    maxlen=max_len,
    padding="post"
)

target_seqs = np.zeros_like(
    input_seqs
)

target_seqs[:, :-1] = input_seqs[:, 1:]
target_seqs[:, -1] = 0


# =========================================================
# Train / Validation Split
# =========================================================

X_train, X_val, y_train, y_val = train_test_split(
    input_seqs,
    target_seqs,
    test_size=0.25,
    random_state=42
)

print(
    f"Training samples: {len(X_train)} | "
    f"Validation samples: {len(X_val)}"
)


# =========================================================
# Build Model
# =========================================================

model = Sequential([

    Embedding(
        input_dim=vocab_size,
        output_dim=args.embedding_dim,
        mask_zero=True
    ),

    LSTM(
        args.lstm_units,
        return_sequences=True
    ),

    Dropout(
        args.dropout
    ),

    LSTM(
        args.lstm_units,
        return_sequences=True
    ),

    Dropout(
        args.dropout
    ),

    Dense(
        vocab_size,
        activation="softmax"
    )
])

optimizer = Adam(
    learning_rate=args.learning_rate,
    clipnorm=1.0
)

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=optimizer,
    metrics=["accuracy"]
)

model.build(
    input_shape=(None, max_len)
)

model.summary()


# =========================================================
# Callbacks
# =========================================================

checkpoint_cb = ModelCheckpoint(
    filepath=args.output,
    save_best_only=True,
    save_weights_only=True,
    monitor="val_loss",
    mode="min",
    verbose=1
)

earlystop_cb = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True,
    verbose=1
)

reduce_lr_cb = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=5,
    verbose=1
)


# =========================================================
# Training
# =========================================================

history = model.fit(
    X_train,
    y_train,
    validation_data=(
        X_val,
        y_val
    ),
    epochs=args.epochs,
    batch_size=args.batch_size,
    callbacks=[
        checkpoint_cb,
        earlystop_cb,
        reduce_lr_cb
    ],
    verbose=1
)

print("\nTraining Complete")
print(f"Best model saved to: {args.output}")
```
